### ISSUE TITLE
Is it possible to make stabilizer work with llvm 4.0?

### ISSUE THREAD

**Issue by shd101wyy** [ccurtsinger/stabilizer#2]
Dear @ccurtsinger ,   

We are now working on a llvm course project, and we are required to use stabilizer to analyze performance.  
However, our project is built based on llvm 4.0.   
So is it possible to build stabilizer in llvm 4.0?  

Thank you very much!
Yiyi

**Comment by ccurtsinger** [comment]
This would probably be quite difficult. The problem is that Stabilizer makes some assumptions about which LLVM IR operations will be converted to position-dependent instructions in the backend. Finding and replacing these was a major issue, and the backend changes in each version. I am actively working on an alternative implementation that would be less sensitive to LLVM changes, so there should be something available soon, but likely not before your course is over.

**Comment by shd101wyy** [comment]
Thank you for your reply.
Yes our course is over already, so don't worry :)

**Comment by tbarbette** [comment]
Hi!

Could you make stabilizer work with a more recent version of LLVM ? Or maybe now there is an equivalent tool you could recommend?

Thanks,
Tom

**Comment by baryluk** [comment]
I am also very interested in using Stabilizer or stabilizer-like tool for testing microbenchmarks and compiler optimizations with more modern toolchain. Any suggestions?
